### ISSUE TITLE
adding control= parameter turns off nthreads= when nthreads= gets passed directly to parglm()

### ISSUE THREAD

**Issue by ajdamico** [boennecd/parglm#4]
hi, hopefully i'm reading my windows task manager correctly..  not sure if you care about this user error, but it tripped me up and i finally realized why my processes were running so slowly

	x <- mtcars[ rep( seq( nrow( mtcars ) ) , 100000 ) , ]

	library(parglm)

	# does multithread
	system.time( parglm::parglm( mpg ~ wt + qsec + cyl + disp + hp + drat + gear + am + vs , data = x , nthreads = 16 ) )

	# does not multithread
	system.time( parglm::parglm( mpg ~ wt + qsec + cyl + disp + hp + drat + gear + am + vs , data = x , nthreads = 16 , control = list(maxit = 25) ) )

	# does multithread
	system.time( parglm::parglm( mpg ~ wt + qsec + cyl + disp + hp + drat + gear + am + vs , data = x , control = list(maxit = 25, nthreads = 16) ) )

**Comment by boennecd** [comment]
It is stated that this is the behavior in `help("parglm")`

> `...` For `parglm`: arguments to be used to form the default `control` argument if it is not supplied directly.

It is as in `glm`. I have intended to keep the API as close to `glm` as possible so I would not call this an error.

**Comment by ajdamico** [comment]
ahh weird.  you definitely are keeping as close to `glm` as possible.  this behavior surprised me.  thanks a lot!


	# both arguments go through
	glm( mpg ~ cyl , data = mtcars , control = list( maxit = 1 , trace = TRUE ) )

	# maxit goes through, trace does not
	glm( mpg ~ cyl , data = mtcars , trace = TRUE , control = list( maxit = 1 ) )

	# trace goes through
	glm( mpg ~ cyl , data = mtcars , trace = TRUE )

	# maxit goes through
	glm( mpg ~ cyl , data = mtcars , maxit = 1 )
