### ISSUE TITLE
tweedie family and out of core

### ISSUE THREAD

**Issue by armgong** [boennecd/parglm#6]
1 Does Parglm support tweedie family?
2 about big dataset can not fit in memory, does parglm support it? Like speedglm function shglm?

**Comment by boennecd** [comment]
> 1 Does Parglm support tweedie family?

Only special cases like the `glm` function in R. 

> 2 about big dataset can not fit in memory, does parglm support it? Like speedglm function shglm?

Currently not. I am not sure how much it will speed up things as I gather the main bottleneck will quickly be how fast you can read from your harddisk. I gather though that one might be able to do something e.g., using some ideas from the iotools package (see https://journal.r-project.org/archive/2017/RJ-2017-001/RJ-2017-001.pdf). 

It is in the TODO file: https://github.com/boennecd/parglm/blob/6cd2ea8fbdce43583d86fc195f0a62a8882cbeb6/TODO#L1-L2

**Comment by armgong** [comment]
1 got it thanks will try some sample 
2 yes chunk wise maybe don’t speed up modeling , but when data is really big, we still need it. Btw nvme ssd or nvme ssd can improve io speed significantly 
 
iotool package pipeline read and mcapply seems better way do this
