### ISSUE TITLE
lots of variables causes crash (not error)

### ISSUE THREAD

**Issue by ajdamico** [boennecd/parglm#8]
hi, the crashing seems inconsistent.. i've gotten this instead of the crash sometimes

	error: chol(): decomposition failed
	Error in parallelglm(X = x, Ys = y, family = paste0(family$family, "_",  :
	  chol(): decomposition failed

here's the code to reproduce the crash, maybe run it a few times and see if it crashes locally for you?

	library(parglm)

	sessionInfo()

	variables <- 10000

	x <- data.frame( a0 = sample( 1:1000 , 1000 ) )

	for( i in seq( variables ) ) x[ , paste0( 'a' , i ) ] <- sample( 1:1000 , 1000 )
	this_formula <- as.formula( paste0( 'a0 ~ ' , paste0( "a" , seq( variables ) , collapse = " + " ) ) )
	parglm( this_formula , data = x , nthreads = parallel::detectCores() )

command window output, you can see the crash (not error) when it just returns to the `C:\Users\anthonyd>` prompt at the very bottom

	Microsoft Windows [Version 10.0.17134.619]
	(c) 2018 Microsoft Corporation. All rights reserved.

	C:\Users\anthonyd>"c:\Program Files\r\R-3.6.0\bin\x64\Rterm.exe"

	R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
	Copyright (C) 2019 The R Foundation for Statistical Computing
	Platform: x86_64-w64-mingw32/x64 (64-bit)

	R is free software and comes with ABSOLUTELY NO WARRANTY.
	You are welcome to redistribute it under certain conditions.
	Type 'license()' or 'licence()' for distribution details.

	  Natural language support but running in an English locale

	R is a collaborative project with many contributors.
	Type 'contributors()' for more information and
	'citation()' on how to cite R or R packages in publications.

	Type 'demo()' for some demos, 'help()' for on-line help, or
	'help.start()' for an HTML browser interface to help.
	Type 'q()' to quit R.

	>
	>
	>
	>
	> library(parglm)
	>
	> sessionInfo()
	R version 3.6.0 (2019-04-26)
	Platform: x86_64-w64-mingw32/x64 (64-bit)
	Running under: Windows 10 x64 (build 17134)

	Matrix products: default

	locale:
	[1] LC_COLLATE=English_United States.1252
	[2] LC_CTYPE=English_United States.1252
	[3] LC_MONETARY=English_United States.1252
	[4] LC_NUMERIC=C
	[5] LC_TIME=English_United States.1252

	attached base packages:
	[1] stats     graphics  grDevices utils     datasets  methods   base

	other attached packages:
	[1] parglm_0.1.3

	loaded via a namespace (and not attached):
	[1] compiler_3.6.0  Matrix_1.2-17   Rcpp_1.0.1      grid_3.6.0
	[5] lattice_0.20-38
	>
	>
	>
	> variables <- 10000
	>
	> x <- data.frame( a0 = sample( 1:1000 , 1000 ) )
	>
	> for( i in seq( variables ) ) x[ , paste0( 'a' , i ) ] <- sample( 1:1000 , 10$
	> this_formula <- as.formula( paste0( 'a0 ~ ' , paste0( "a" , seq( variables )$
	> parglm( this_formula , data = x , nthreads = parallel::detectCores() )

	C:\Users\anthonyd>

**Comment by boennecd** [comment]
Thanks for reporting the issue. This reproduces the error (runs faster)

```r
library(parglm)
variables <- 1000L
n <- 20L

set.seed(1)
x <- cbind(data.frame(a0 = sample.int(n, n)),
           replicate(variables, sample(n, n)))

parglm(a0 ~ ., data = x, nthreads = 3L)
```

The error is a segfault which occurs due to an invalid read when there are fewer observation than covariates. I never intended the package to be used in this case and will make sure `stop` is called if there is fewer observations than covariates.
