### ISSUE TITLE
larger data set still crashes (not error)

### ISSUE THREAD

**Issue by ajdamico** [boennecd/parglm#9]
hi, ten million records x 501 columns still crashes--  :-/   thank you for your time with these!

	library(parglm)

	sessionInfo()

	variables <- 500L
	n <- 10000000L

	set.seed(1)
	x <- cbind(data.frame(a0 = sample.int(n, n)),
			   replicate(variables, sample(n, n)))

	parglm(a0 ~ ., data = x, nthreads = 3L)

console output:

	C:\Users\AnthonyD>"c:\Program Files\r\R-3.6.0\bin\x64\Rterm.exe"

	R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
	Copyright (C) 2019 The R Foundation for Statistical Computing
	Platform: x86_64-w64-mingw32/x64 (64-bit)

	R is free software and comes with ABSOLUTELY NO WARRANTY.
	You are welcome to redistribute it under certain conditions.
	Type 'license()' or 'licence()' for distribution details.

	  Natural language support but running in an English locale

	R is a collaborative project with many contributors.
	Type 'contributors()' for more information and
	'citation()' on how to cite R or R packages in publications.

	Type 'demo()' for some demos, 'help()' for on-line help, or
	'help.start()' for an HTML browser interface to help.
	Type 'q()' to quit R.

	> library(parglm)
	> variables <- 500L
	> n <- 10000000L
	>
	> set.seed(1)
	> x <- cbind(data.frame(a0 = sample.int(n, n)),
	+            replicate(variables, sample(n, n)))
	>
	> parglm(a0 ~ ., data = x, nthreads = 3L)

	C:\Users\AnthonyD>

**Comment by boennecd** [comment]
My computer crashes with this code but I guess it is because I do not have enough RAM on my machine 

```r
library(parglm)
variables <- 100L
n <- 10000000L

set.seed(1)
x <- cbind(data.frame(a0 = sample.int(n, n)),
           matrix(runif(n * variables), nc = variables))
gc()
x <- cbind(x, matrix(runif(n * variables), nc = variables))
names(x)[2:ncol(x)] <- paste0("X", 2:ncol(x))
gc()

parglm(a0 ~ ., data = x, nthreads = 3L)
``` 

How much RAM do you have on your machine?

**Comment by ajdamico** [comment]
hi, 1.5TB..  parglm is most useful for huge datasets so hopefully you can get access to a larger box to test this out?  it is hitting some limit and crashing R but definitely not ram  :(

**Comment by boennecd** [comment]
I see. Thanks for reporting the issue. I wanted to make sure it was not due to RAM issues. I could not reproduce the error otherwise. E.g., 

```r
library(parglm)

sessionInfo()

variables <- 50L
n <- 10000000L

set.seed(1)
x <- cbind(data.frame(a0 = sample.int(n, n)),
           replicate(variables, sample(n, n)))
gc()

parglm(a0 ~ ., data = x, nthreads = 3L)
```

works fine on my machine (Ubuntu 18.04). Can you show the `sessionInfo()` output? Can you confirm the the code in [this post](https://github.com/boennecd/parglm/issues/9#issuecomment-498066781) also causes a crash (it is faster). I will then try to figure out what is going on with an AWS instance. Maybe an `unsigned int` somewhere which could be the cause. This seems quite possible.

**Comment by ajdamico** [comment]
hi, [this post](https://github.com/boennecd/parglm/issues/9#issuecomment-498066781) definitely does *not* cause a crash or an error.  if i increase `variables <- 400L` then i get a different error?  see below with session info as well..  thanks!



	Microsoft Windows [Version 6.3.9600]
	(c) 2013 Microsoft Corporation. All rights reserved.

	C:\Users\AnthonyD>"C:\Program Files\R\R-3.6.0\bin\x64\Rterm.exe"

	R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
	Copyright (C) 2019 The R Foundation for Statistical Computing
	Platform: x86_64-w64-mingw32/x64 (64-bit)

	R is free software and comes with ABSOLUTELY NO WARRANTY.
	You are welcome to redistribute it under certain conditions.
	Type 'license()' or 'licence()' for distribution details.

	  Natural language support but running in an English locale

	R is a collaborative project with many contributors.
	Type 'contributors()' for more information and
	'citation()' on how to cite R or R packages in publications.

	Type 'demo()' for some demos, 'help()' for on-line help, or
	'help.start()' for an HTML browser interface to help.
	Type 'q()' to quit R.

	>
	> library(parglm)
	> sessionInfo()
	R version 3.6.0 (2019-04-26)
	Platform: x86_64-w64-mingw32/x64 (64-bit)
	Running under: Windows Server 2012 R2 x64 (build 9600)

	Matrix products: default

	locale:
	[1] LC_COLLATE=English_United States.1252
	[2] LC_CTYPE=English_United States.1252
	[3] LC_MONETARY=English_United States.1252
	[4] LC_NUMERIC=C
	[5] LC_TIME=English_United States.1252

	attached base packages:
	[1] stats     graphics  grDevices utils     datasets  methods   base

	other attached packages:
	[1] parglm_0.1.4

	loaded via a namespace (and not attached):
	[1] compiler_3.6.0  Matrix_1.2-17   Rcpp_1.0.1      grid_3.6.0
	[5] lattice_0.20-38
	> variables <- 400L
	> n <- 10000000L
	>
	> set.seed(1)
	> x <- cbind(data.frame(a0 = sample.int(n, n)),
	+            matrix(runif(n * variables), nc = variables))
	Error in runif(n * variables) : invalid arguments
	In addition: Warning message:
	In n * variables : NAs produced by integer overflow

**Comment by ajdamico** [comment]
hi @boennecd i sent an e-mail to boennecd at gmail about computing resources, don't mean to rush you but want to make sure that was the correct address.  thanks!

**Comment by boennecd** [comment]
I suspect the error is an 
 
1. integer overflow error.
2. issues with memory (e.g., the amount of available RAM or lag of available continuous memory). 

I have tried to run the following code on a r5.2xlarge AWS instance using the Amazon Linux AMI image.

```r
if(!require(parglm)){
  install.packages("devtools")
  devtools::install_github("boennecd/parglm", ref = "f2e8696c8")
}

library(parglm)
run_old <- FALSE
if(run_old){
  rm(list = ls())
  variables <- 500L
  n <- 4000000L
  set.seed(1)
  x <- data.frame(a0 = sample.int(n, n),
                  replicate(variables, sample(n, n)))
  
  print(gc())
  parglm(a0 ~ ., data = x, nthreads = 8L)
}

#####
# new code
# want it to fail on `r5.2xlarge` instance? If so, set 
# the next variable to`TRUE` and run the code below a few times
rm(list = ls())
gc()
do_fail <- FALSE

variables <- 500L
n <- if(do_fail) 4000000L else 3000000L
set.seed(1)
x <- data.frame(z = factor(sample.int(variables, n, replace = TRUE)))
x <- data.frame(a0 = sample.int(n, n), 
                matrix(as.integer(model.matrix( ~ ., x)), n, variables))

# required memory (GB) is:
# ~ model.matrix + QR
(variables * (n / 1000000000L)) * 8L * 2L +
  # ~ x + model.frame copy
  (variables * (n / 1000000000L)) * 4L * 2L

gc()
parglm(a0 ~ ., data = x, control = parglm.control(nthreads = 8, maxit = 1L))
```

When `do_fail` is `FALSE` then 

 - I get a `std::bad_alloc` error, the R proces returns but it seems from `htop` that there may be some leaked memory. 
 - I get a `std::bad_alloc` error and the R console hangs (but is working). I waited more than an hour and nothing happened. 
 - the R process hangs and nothings happens. 

Can you confirm that this too fails on your end? You may need to vary `n`.

I suspect that I may get further either using clang's address sanitizer or gdb (the latter is likely slow though). I am not sure how to check 1. but 2. should be captured. I think it is the latter given that I saw that calling `gc()` helped mitigate the issue. If this is the case then an ideal solution is one where the error is captured properly, all memory allocations are freed and the R console returns back.

**Comment by ajdamico** [comment]
hi, thanks for continuing to look at this.  i tested up to `n <- 8000000L` and that worked, then `n <- 12000000L` crashed..

**Comment by boennecd** [comment]
Yesterday evening, I tried to use an c5.large instance instead (only 4GB of RAM and more single processor computing power relative to the RAMs). I ran it with 

```r
# ...
n <- if(do_fail)  250000L else 150000L
# ...
parglm(a0 ~ ., data = x, control = parglm.control(nthreads = 2, maxit = 1L))
```
and got the same error. Thus, it this seems to confirm that it is a memory issue and gives me a fast way to reproduce the error.

**Comment by ajdamico** [comment]
hi, my test was a crash not an error..

**Comment by boennecd** [comment]
Sorry for the infrequent replies. I have tried to run it from the terminal instead using `R  -e "source('test-script.R')"` and `R -d gdb -e "source('test-script.R')"` where `test-script.R` has the code from [this comment](https://github.com/boennecd/parglm/issues/9#issuecomment-533080042). This just gives 

```
Error in parallelglm(X = x, Ys = y, family = paste0(family$family, "_",  :
  std::bad_alloc
```

and does not crash or become unresponsive whereas it does if I run it from Rstudio server. Can you confirm whether you have the samme issue when running it from the console if you did not already (that is, not using Rstudio if you did)?

**Comment by ajdamico** [comment]
closing because this seems to be fixed..thanks and hooray!
